### PR TITLE
multi-input form control now allows users to create new entities with popover form

### LINKED ISSUE #1244: allow users to create new drugs from the drug multi-input fields

### PR DESCRIPTION
**Pull request by jmcmichael**
In order to allow users to create a new drug not found in the CIViC database, the multiInput form field control needed to be updated with a 'new entity' button and popover that shows a new entity form. The Add Evidence drug field has been updated to use this new feature, I'll shortly be updating the other forms that use multiInput.

New button next to the Add/Remove row buttons:
Screenshot 2019-11-21 12 11 11

Displays a popover when clicked:
Screenshot 2019-11-21 12 03 00

User enters a new drug name:
Screenshot 2019-11-21 12 03 51

If new drug added successfully, confirmation msg appears along with a button allowing the user to immediately add it to the list:
Screenshot 2019-11-21 12 03 58

After 'Add' button clicked:
Screenshot 2019-11-21 12 04 03

If the new drug already exists, a conflict msg is shown, along with the same 'Add' button:
Screenshot 2019-11-21 12 04 19

Closes #1244, requires griffithlab/civic-server#549.

### CODE REVIEW

**Comment by jmcmichael** [comment]
Note that the entity name ('Drug' in this case) and popover form are configuration parameters, so the field control can be adapted to manage any list of CIViC entities.

**Comment by jmcmichael** [comment]
OK this is ready to deploy to staging for testing.

**Comment by susannasiebert** [comment]
I assume this requires https://github.com/griffithlab/civic-server/pull/549

Edit: Sorry, just noticed you mentioned that at the end of the PR descriptions

**Comment by jmcmichael** [comment]
Yeah, forgot to mention that.

**Review by susannasiebert — APPROVED** [review]
+1

**Pull request merged**
