### PR TITLE
revise variant origin attributes

### PR DESCRIPTION
**Pull request by ahwagner**
Revising variant origin attributes for rare and common germline to align with documentation and concisely state criteria.

### CODE REVIEW

**Comment by ahwagner** [comment]
@obigriffith or @malachig this is a definitional change for clarity and alignment with documentation, requires your approval for correctness.

@jmcmichael, please confirm that this isn't breaking anything.

**Comment by ahwagner** [comment]
See related fixes in PR for civic-docs: https://github.com/griffithlab/civic-docs/pull/45

**Review by jmcmichael — APPROVED** [review]
looks good!

**Review by kkrysiak — APPROVED** [review]
Looks good

**Pull request merged**
